module Plaza
  class AutocompleteRequest = Plaza::Models::AutocompleteRequest

  class AutocompleteResult = Plaza::Models::AutocompleteResult

  class BatchRequest = Plaza::Models::BatchRequest

  class Dataset = Plaza::Models::Dataset

  class DatasetCreateParams = Plaza::Models::DatasetCreateParams

  class DatasetDeleteParams = Plaza::Models::DatasetDeleteParams

  class DatasetList = Plaza::Models::DatasetList

  class DatasetListParams = Plaza::Models::DatasetListParams

  class DatasetRetrieveParams = Plaza::Models::DatasetRetrieveParams

  class ElevationLookupParams = Plaza::Models::ElevationLookupParams

  class ElevationLookupRequest = Plaza::Models::ElevationLookupRequest

  class ElevationLookupResult = Plaza::Models::ElevationLookupResult

  class ElevationProfileParams = Plaza::Models::ElevationProfileParams

  class ElevationProfileRequest = Plaza::Models::ElevationProfileRequest

  class ElevationProfileResult = Plaza::Models::ElevationProfileResult

  class Error = Plaza::Models::Error

  class FeatureBatchParams = Plaza::Models::FeatureBatchParams

  class FeatureCollection = Plaza::Models::FeatureCollection

  class FeatureQueryParams = Plaza::Models::FeatureQueryParams

  class FeatureRetrieveParams = Plaza::Models::FeatureRetrieveParams

  class GeocodeAutocompleteParams = Plaza::Models::GeocodeAutocompleteParams

  class GeocodeBatchParams = Plaza::Models::GeocodeBatchParams

  class GeocodeForwardParams = Plaza::Models::GeocodeForwardParams

  class GeocodeForwardRequest = Plaza::Models::GeocodeForwardRequest

  class GeocodeResult = Plaza::Models::GeocodeResult

  class GeocodeReverseParams = Plaza::Models::GeocodeReverseParams

  class GeocodeReverseRequest = Plaza::Models::GeocodeReverseRequest

  class GeocodingFeature = Plaza::Models::GeocodingFeature

  class GeoJsonFeature = Plaza::Models::GeoJsonFeature

  module Geometry = Plaza::Models::Geometry

  class IsochroneRequest = Plaza::Models::IsochroneRequest

  class LineStringGeometry = Plaza::Models::LineStringGeometry

  class MapMatchMatchParams = Plaza::Models::MapMatchMatchParams

  class MapMatchRequest = Plaza::Models::MapMatchRequest

  class MapMatchResult = Plaza::Models::MapMatchResult

  class MatrixRequest = Plaza::Models::MatrixRequest

  MatrixResult: Plaza::Internal::Type::Converter

  class MultiLineStringGeometry = Plaza::Models::MultiLineStringGeometry

  class MultiPointGeometry = Plaza::Models::MultiPointGeometry

  class MultiPolygonGeometry = Plaza::Models::MultiPolygonGeometry

  class NearestRequest = Plaza::Models::NearestRequest

  class NearestResult = Plaza::Models::NearestResult

  class OptimizeCompletedResult = Plaza::Models::OptimizeCompletedResult

  class OptimizeCreateParams = Plaza::Models::OptimizeCreateParams

  class OptimizeJobStatus = Plaza::Models::OptimizeJobStatus

  class OptimizeProcessingResult = Plaza::Models::OptimizeProcessingResult

  class OptimizeRequest = Plaza::Models::OptimizeRequest

  module OptimizeResult = Plaza::Models::OptimizeResult

  class OptimizeRetrieveParams = Plaza::Models::OptimizeRetrieveParams

  class PlazaqlQuery = Plaza::Models::PlazaqlQuery

  class PointGeometry = Plaza::Models::PointGeometry

  class PolygonGeometry = Plaza::Models::PolygonGeometry

  class QueryExecuteParams = Plaza::Models::QueryExecuteParams

  class ReverseGeocodeResult = Plaza::Models::ReverseGeocodeResult

  class RouteRequest = Plaza::Models::RouteRequest

  class RouteResult = Plaza::Models::RouteResult

  class RoutingIsochroneParams = Plaza::Models::RoutingIsochroneParams

  class RoutingMatrixParams = Plaza::Models::RoutingMatrixParams

  class RoutingNearestParams = Plaza::Models::RoutingNearestParams

  class RoutingRouteParams = Plaza::Models::RoutingRouteParams

  class SearchQueryParams = Plaza::Models::SearchQueryParams

  class SpatialPredicate = Plaza::Models::SpatialPredicate

  class TileGetParams = Plaza::Models::TileGetParams

  class ValidationError = Plaza::Models::ValidationError
end
