module Plaza
  module Resources
    class Elements
      def retrieve: (
        Integer id,
        type: String,
        ?request_options: Plaza::request_opts
      ) -> Plaza::GeoJsonFeature

      def batch: (
        elements: ::Array[Plaza::BatchRequest::Element],
        ?request_options: Plaza::request_opts
      ) -> Plaza::FeatureCollection

      def lookup: (
        ?request_options: Plaza::request_opts
      ) -> Plaza::GeoJsonFeature

      def nearby: (
        ?lat: Float,
        ?limit: Integer,
        ?lng: Float,
        ?near: String,
        ?output_buffer: Float,
        ?output_centroid: bool,
        ?output_fields: String,
        ?output_geometry: bool,
        ?output_include: String,
        ?output_precision: Integer,
        ?output_simplify: Float,
        ?output_sort: String,
        ?radius: Integer,
        ?request_options: Plaza::request_opts
      ) -> Plaza::FeatureCollection

      def nearby_post: (
        ?lat: Float,
        ?limit: Integer,
        ?lng: Float,
        ?near: String,
        ?output_buffer: Float,
        ?output_centroid: bool,
        ?output_fields: String,
        ?output_geometry: bool,
        ?output_include: String,
        ?output_precision: Integer,
        ?output_simplify: Float,
        ?output_sort: String,
        ?radius: Integer,
        ?request_options: Plaza::request_opts
      ) -> Plaza::FeatureCollection

      def query: (
        ?bbox: String,
        ?contains: String,
        ?crosses: String,
        ?cursor: String,
        ?format_: String,
        ?h3: String,
        ?intersects: String,
        ?limit: Integer,
        ?near: String,
        ?output_buffer: Float,
        ?output_centroid: bool,
        ?output_fields: String,
        ?output_geometry: bool,
        ?output_include: String,
        ?output_precision: Integer,
        ?output_simplify: Float,
        ?output_sort: String,
        ?radius: Float,
        ?touches: String,
        ?type: String,
        ?within: String,
        ?request_options: Plaza::request_opts
      ) -> Plaza::FeatureCollection

      def query_post: (
        ?bbox: String,
        ?contains: String,
        ?crosses: String,
        ?cursor: String,
        ?format_: String,
        ?h3: String,
        ?intersects: String,
        ?limit: Integer,
        ?near: String,
        ?output_buffer: Float,
        ?output_centroid: bool,
        ?output_fields: String,
        ?output_geometry: bool,
        ?output_include: String,
        ?output_precision: Integer,
        ?output_simplify: Float,
        ?output_sort: String,
        ?radius: Float,
        ?touches: String,
        ?type: String,
        ?within: String,
        ?request_options: Plaza::request_opts
      ) -> Plaza::FeatureCollection

      def initialize: (client: Plaza::Client) -> void
    end
  end
end
