module Plaza
  module Resources
    class Elevation
      def lookup: (
        geometry: Plaza::Models::ElevationLookupRequest::geometry,
        ?format_: String,
        ?request_options: Plaza::request_opts
      ) -> Plaza::ElevationLookupResult

      def profile: (
        geometry: Plaza::LineStringGeometry,
        ?request_options: Plaza::request_opts
      ) -> Plaza::ElevationProfileResult

      def initialize: (client: Plaza::Client) -> void
    end
  end
end
