module Plaza
  module Resources
    class Elevation
      def batch: (
        geometry: Plaza::GeoJsonGeometry,
        ?request_options: Plaza::request_opts
      ) -> Plaza::ElevationBatchResult

      def lookup: (
        ?lat: Float,
        ?lng: Float,
        ?locations: String,
        ?request_options: Plaza::request_opts
      ) -> Plaza::ElevationLookupResult

      def profile: (
        geometry: Plaza::GeoJsonGeometry,
        ?request_options: Plaza::request_opts
      ) -> Plaza::ElevationProfileResult

      def initialize: (client: Plaza::Client) -> void
    end
  end
end
