module Plaza
  module Resources
    class Geocode
      def autocomplete: (
        q: String,
        ?format_: String,
        ?country_code: String?,
        ?focus: Plaza::PointGeometry?,
        ?lang: String?,
        ?layer: String?,
        ?limit: Integer?,
        ?request_options: Plaza::request_opts
      ) -> Plaza::AutocompleteResult

      def batch: (
        addresses: ::Array[String],
        ?request_options: Plaza::request_opts
      ) -> Plaza::Models::GeocodeBatchResponse

      def forward: (
        q: String,
        ?format_: String,
        ?country_code: String?,
        ?focus: Plaza::PointGeometry?,
        ?lang: String?,
        ?layer: String?,
        ?limit: Integer?,
        ?request_options: Plaza::request_opts
      ) -> Plaza::GeocodeResult

      def reverse: (
        geometry: Plaza::PointGeometry,
        ?format_: String,
        ?lang: String?,
        ?limit: Integer?,
        ?radius: Float?,
        ?request_options: Plaza::request_opts
      ) -> Plaza::ReverseGeocodeResult

      def initialize: (client: Plaza::Client) -> void
    end
  end
end
