module Plaza
  module Resources
    class MapMatch
      def match: (
        geometry: Plaza::LineStringGeometry,
        ?radiuses: ::Array[Float]?,
        ?request_options: Plaza::request_opts
      ) -> Plaza::MapMatchResult

      def initialize: (client: Plaza::Client) -> void
    end
  end
end
