module Plaza
  module Resources
    class Optimize
      def create: (
        waypoints: Plaza::MultiPointGeometry,
        ?format_: String,
        ?mode: Plaza::Models::OptimizeRequest::mode,
        ?roundtrip: bool,
        ?request_options: Plaza::request_opts
      ) -> Plaza::Models::optimize_result

      def retrieve: (
        String job_id,
        ?request_options: Plaza::request_opts
      ) -> Plaza::OptimizeJobStatus

      def initialize: (client: Plaza::Client) -> void
    end
  end
end
