module Plaza
  module Resources
    class Query
      def execute: (
        data: String,
        ?format_: String,
        ?request_options: Plaza::request_opts
      ) -> Plaza::FeatureCollection

      def initialize: (client: Plaza::Client) -> void
    end
  end
end
