module Plaza
  module Resources
    class Routing
      def isochrone: (
        geometry: Plaza::PointGeometry,
        time: ::Array[Integer],
        ?format_: String,
        ?mode: Plaza::Models::IsochroneRequest::mode,
        ?request_options: Plaza::request_opts
      ) -> Plaza::Models::RoutingIsochroneResponse

      def matrix: (
        destinations: ::Array[Plaza::PointGeometry],
        origins: ::Array[Plaza::PointGeometry],
        ?annotations: String,
        ?fallback_speed: Float?,
        ?mode: Plaza::Models::MatrixRequest::mode,
        ?request_options: Plaza::request_opts
      ) -> Plaza::Models::matrix_result

      def nearest: (
        geometry: Plaza::PointGeometry,
        ?radius: Float?,
        ?request_options: Plaza::request_opts
      ) -> Plaza::NearestResult

      def route: (
        destination: Plaza::PointGeometry,
        origin: Plaza::PointGeometry,
        ?format_: String,
        ?alternatives: Integer,
        ?annotations: bool,
        ?depart_at: Time?,
        ?ev: Plaza::RouteRequest::Ev?,
        ?exclude: String?,
        ?geometries: Plaza::Models::RouteRequest::geometries,
        ?mode: Plaza::Models::RouteRequest::mode,
        ?overview: Plaza::Models::RouteRequest::overview,
        ?steps: bool,
        ?traffic_model: Plaza::Models::RouteRequest::traffic_model?,
        ?waypoints: ::Array[Plaza::PointGeometry]?,
        ?request_options: Plaza::request_opts
      ) -> Plaza::RouteResult

      def initialize: (client: Plaza::Client) -> void
    end
  end
end
