module PlazaSDK
  module Models
    type batch_request = { elements: ::Array[PlazaSDK::BatchRequest::Element] }

    class BatchRequest < PlazaSDK::Internal::Type::BaseModel
      attr_accessor elements: ::Array[PlazaSDK::BatchRequest::Element]

      def initialize: (
        elements: ::Array[PlazaSDK::BatchRequest::Element]
      ) -> void

      def to_hash: -> { elements: ::Array[PlazaSDK::BatchRequest::Element] }

      type element =
        { id: Integer, type: PlazaSDK::Models::BatchRequest::Element::type_ }

      class Element < PlazaSDK::Internal::Type::BaseModel
        attr_accessor id: Integer

        attr_accessor type: PlazaSDK::Models::BatchRequest::Element::type_

        def initialize: (
          id: Integer,
          type: PlazaSDK::Models::BatchRequest::Element::type_
        ) -> void

        def to_hash: -> {
          id: Integer,
          type: PlazaSDK::Models::BatchRequest::Element::type_
        }

        type type_ = :node | :way | :relation

        module Type
          extend PlazaSDK::Internal::Type::Enum

          NODE: :node
          WAY: :way
          RELATION: :relation

          def self?.values: -> ::Array[PlazaSDK::Models::BatchRequest::Element::type_]
        end
      end
    end
  end
end
