module PlazaSDK
  module Models
    type elevation_profile_request = { geometry: PlazaSDK::GeoJsonGeometry }

    class ElevationProfileRequest < PlazaSDK::Internal::Type::BaseModel
      attr_accessor geometry: PlazaSDK::GeoJsonGeometry

      def initialize: (geometry: PlazaSDK::GeoJsonGeometry) -> void

      def to_hash: -> { geometry: PlazaSDK::GeoJsonGeometry }
    end
  end
end
