module PlazaSDK
  module Models
    type feature_collection =
      {
        features: ::Array[PlazaSDK::GeoJsonFeature],
        type: PlazaSDK::Models::FeatureCollection::type_
      }

    class FeatureCollection < PlazaSDK::Internal::Type::BaseModel
      attr_accessor features: ::Array[PlazaSDK::GeoJsonFeature]

      attr_accessor type: PlazaSDK::Models::FeatureCollection::type_

      def initialize: (
        features: ::Array[PlazaSDK::GeoJsonFeature],
        type: PlazaSDK::Models::FeatureCollection::type_
      ) -> void

      def to_hash: -> {
        features: ::Array[PlazaSDK::GeoJsonFeature],
        type: PlazaSDK::Models::FeatureCollection::type_
      }

      type type_ = :FeatureCollection

      module Type
        extend PlazaSDK::Internal::Type::Enum

        FEATURE_COLLECTION: :FeatureCollection

        def self?.values: -> ::Array[PlazaSDK::Models::FeatureCollection::type_]
      end
    end
  end
end
