module PlazaSDK
  module Models
    type geo_json_geometry =
      {
        coordinates: PlazaSDK::Models::GeoJsonGeometry::coordinates,
        type: PlazaSDK::Models::GeoJsonGeometry::type_
      }

    class GeoJsonGeometry < PlazaSDK::Internal::Type::BaseModel
      attr_accessor coordinates: PlazaSDK::Models::GeoJsonGeometry::coordinates

      attr_accessor type: PlazaSDK::Models::GeoJsonGeometry::type_

      def initialize: (
        coordinates: PlazaSDK::Models::GeoJsonGeometry::coordinates,
        type: PlazaSDK::Models::GeoJsonGeometry::type_
      ) -> void

      def to_hash: -> {
        coordinates: PlazaSDK::Models::GeoJsonGeometry::coordinates,
        type: PlazaSDK::Models::GeoJsonGeometry::type_
      }

      type coordinates =
        ::Array[Float]
        | ::Array[::Array[Float]]
        | ::Array[::Array[::Array[Float]]]
        | ::Array[::Array[::Array[::Array[Float]]]]

      module Coordinates
        extend PlazaSDK::Internal::Type::Union

        def self?.variants: -> ::Array[PlazaSDK::Models::GeoJsonGeometry::coordinates]

        FloatArray: PlazaSDK::Internal::Type::Converter

        UnionMember1Array: PlazaSDK::Internal::Type::Converter

        UnionMember2Array: PlazaSDK::Internal::Type::Converter

        UnionMember3Array: PlazaSDK::Internal::Type::Converter
      end

      type type_ =
        :Point
        | :LineString
        | :Polygon
        | :MultiPoint
        | :MultiLineString
        | :MultiPolygon

      module Type
        extend PlazaSDK::Internal::Type::Enum

        POINT: :Point
        LINE_STRING: :LineString
        POLYGON: :Polygon
        MULTI_POINT: :MultiPoint
        MULTI_LINE_STRING: :MultiLineString
        MULTI_POLYGON: :MultiPolygon

        def self?.values: -> ::Array[PlazaSDK::Models::GeoJsonGeometry::type_]
      end
    end
  end
end
