module PlazaSDK
  module Models
    type geo_json_feature =
      {
        geometry: PlazaSDK::GeoJsonGeometry,
        properties: ::Hash[Symbol, top],
        type: PlazaSDK::Models::GeoJsonFeature::type_,
        id: String,
        osm_id: Integer
      }

    class GeoJsonFeature < PlazaSDK::Internal::Type::BaseModel
      attr_accessor geometry: PlazaSDK::GeoJsonGeometry

      attr_accessor properties: ::Hash[Symbol, top]

      attr_accessor type: PlazaSDK::Models::GeoJsonFeature::type_

      attr_reader id: String?

      def id=: (String) -> String

      attr_reader osm_id: Integer?

      def osm_id=: (Integer) -> Integer

      def initialize: (
        geometry: PlazaSDK::GeoJsonGeometry,
        properties: ::Hash[Symbol, top],
        type: PlazaSDK::Models::GeoJsonFeature::type_,
        ?id: String,
        ?osm_id: Integer
      ) -> void

      def to_hash: -> {
        geometry: PlazaSDK::GeoJsonGeometry,
        properties: ::Hash[Symbol, top],
        type: PlazaSDK::Models::GeoJsonFeature::type_,
        id: String,
        osm_id: Integer
      }

      type type_ = :Feature

      module Type
        extend PlazaSDK::Internal::Type::Enum

        FEATURE: :Feature

        def self?.values: -> ::Array[PlazaSDK::Models::GeoJsonFeature::type_]
      end
    end
  end
end
