module PlazaSDK
  module Models
    type matrix_request =
      {
        destinations: PlazaSDK::GeoJsonGeometry,
        origins: PlazaSDK::GeoJsonGeometry,
        mode: PlazaSDK::Models::MatrixRequest::mode
      }

    class MatrixRequest < PlazaSDK::Internal::Type::BaseModel
      attr_accessor destinations: PlazaSDK::GeoJsonGeometry

      attr_accessor origins: PlazaSDK::GeoJsonGeometry

      attr_reader mode: PlazaSDK::Models::MatrixRequest::mode?

      def mode=: (
        PlazaSDK::Models::MatrixRequest::mode
      ) -> PlazaSDK::Models::MatrixRequest::mode

      def initialize: (
        destinations: PlazaSDK::GeoJsonGeometry,
        origins: PlazaSDK::GeoJsonGeometry,
        ?mode: PlazaSDK::Models::MatrixRequest::mode
      ) -> void

      def to_hash: -> {
        destinations: PlazaSDK::GeoJsonGeometry,
        origins: PlazaSDK::GeoJsonGeometry,
        mode: PlazaSDK::Models::MatrixRequest::mode
      }

      type mode = :auto | :foot | :bicycle

      module Mode
        extend PlazaSDK::Internal::Type::Enum

        AUTO: :auto
        FOOT: :foot
        BICYCLE: :bicycle

        def self?.values: -> ::Array[PlazaSDK::Models::MatrixRequest::mode]
      end
    end
  end
end
