module PlazaSDK
  module Models
    type optimize_retrieve_params =
      { job_id: String } & PlazaSDK::Internal::Type::request_parameters

    class OptimizeRetrieveParams < PlazaSDK::Internal::Type::BaseModel
      extend PlazaSDK::Internal::Type::RequestParameters::Converter
      include PlazaSDK::Internal::Type::RequestParameters

      attr_accessor job_id: String

      def initialize: (
        job_id: String,
        ?request_options: PlazaSDK::request_opts
      ) -> void

      def to_hash: -> {
        job_id: String,
        request_options: PlazaSDK::RequestOptions
      }
    end
  end
end
