module PlazaSDK
  module Models
    type overpass_query = { data: String }

    class OverpassQuery < PlazaSDK::Internal::Type::BaseModel
      attr_accessor data: String

      def initialize: (data: String) -> void

      def to_hash: -> { data: String }
    end
  end
end
