module PlazaSDK
  module Models
    type query_overpass_params =
      {  } & PlazaSDK::Internal::Type::request_parameters

    class QueryOverpassParams < PlazaSDK::Models::OverpassQuery
      extend PlazaSDK::Internal::Type::RequestParameters::Converter
      include PlazaSDK::Internal::Type::RequestParameters

      def initialize: (?request_options: PlazaSDK::request_opts) -> void

      def to_hash: -> { request_options: PlazaSDK::RequestOptions }
    end
  end
end
