# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "plaza_sdk/version"
require_relative "plaza_sdk/internal/util"
require_relative "plaza_sdk/internal/type/converter"
require_relative "plaza_sdk/internal/type/unknown"
require_relative "plaza_sdk/internal/type/boolean"
require_relative "plaza_sdk/internal/type/file_input"
require_relative "plaza_sdk/internal/type/enum"
require_relative "plaza_sdk/internal/type/union"
require_relative "plaza_sdk/internal/type/array_of"
require_relative "plaza_sdk/internal/type/hash_of"
require_relative "plaza_sdk/internal/type/base_model"
require_relative "plaza_sdk/internal/type/base_page"
require_relative "plaza_sdk/internal/type/request_parameters"
require_relative "plaza_sdk/internal"
require_relative "plaza_sdk/request_options"
require_relative "plaza_sdk/file_part"
require_relative "plaza_sdk/errors"
require_relative "plaza_sdk/internal/transport/base_client"
require_relative "plaza_sdk/internal/transport/pooled_net_requester"
require_relative "plaza_sdk/client"
require_relative "plaza_sdk/models/batch_request"
require_relative "plaza_sdk/models/elevation_profile_request"
require_relative "plaza_sdk/models/map_match_request"
require_relative "plaza_sdk/models/optimize_request"
require_relative "plaza_sdk/models/overpass_query"
require_relative "plaza_sdk/models/sparql_query"
require_relative "plaza_sdk/models/matrix_request"
require_relative "plaza_sdk/models/route_request"
require_relative "plaza_sdk/models/autocomplete_result"
require_relative "plaza_sdk/models/dataset"
require_relative "plaza_sdk/models/dataset_create_params"
require_relative "plaza_sdk/models/dataset_delete_params"
require_relative "plaza_sdk/models/dataset_features_params"
require_relative "plaza_sdk/models/dataset_list"
require_relative "plaza_sdk/models/dataset_list_params"
require_relative "plaza_sdk/models/dataset_retrieve_params"
require_relative "plaza_sdk/models/element_batch_params"
require_relative "plaza_sdk/models/element_nearby_params"
require_relative "plaza_sdk/models/element_query_params"
require_relative "plaza_sdk/models/element_retrieve_params"
require_relative "plaza_sdk/models/elevation_batch_params"
require_relative "plaza_sdk/models/elevation_batch_result"
require_relative "plaza_sdk/models/elevation_lookup_params"
require_relative "plaza_sdk/models/elevation_lookup_result"
require_relative "plaza_sdk/models/elevation_profile_params"
require_relative "plaza_sdk/models/elevation_profile_result"
require_relative "plaza_sdk/models/error"
require_relative "plaza_sdk/models/feature_collection"
require_relative "plaza_sdk/models/geocode_autocomplete_params"
require_relative "plaza_sdk/models/geocode_batch_params"
require_relative "plaza_sdk/models/geocode_batch_response"
require_relative "plaza_sdk/models/geocode_forward_params"
require_relative "plaza_sdk/models/geocode_result"
require_relative "plaza_sdk/models/geocode_reverse_params"
require_relative "plaza_sdk/models/geocoding_feature"
require_relative "plaza_sdk/models/geo_json_feature"
require_relative "plaza_sdk/models/geo_json_geometry"
require_relative "plaza_sdk/models/map_match_match_params"
require_relative "plaza_sdk/models/map_match_result"
require_relative "plaza_sdk/models/matrix_result"
require_relative "plaza_sdk/models/nearest_result"
require_relative "plaza_sdk/models/optimize_completed_result"
require_relative "plaza_sdk/models/optimize_create_params"
require_relative "plaza_sdk/models/optimize_job_status"
require_relative "plaza_sdk/models/optimize_processing_result"
require_relative "plaza_sdk/models/optimize_result"
require_relative "plaza_sdk/models/optimize_retrieve_params"
require_relative "plaza_sdk/models/query_overpass_params"
require_relative "plaza_sdk/models/query_sparql_params"
require_relative "plaza_sdk/models/reverse_geocode_result"
require_relative "plaza_sdk/models/route_result"
require_relative "plaza_sdk/models/routing_isochrone_params"
require_relative "plaza_sdk/models/routing_matrix_params"
require_relative "plaza_sdk/models/routing_nearest_params"
require_relative "plaza_sdk/models/routing_route_params"
require_relative "plaza_sdk/models/search_query_params"
require_relative "plaza_sdk/models/sparql_result"
require_relative "plaza_sdk/models/tile_get_params"
require_relative "plaza_sdk/models"
require_relative "plaza_sdk/resources/datasets"
require_relative "plaza_sdk/resources/elements"
require_relative "plaza_sdk/resources/elevation"
require_relative "plaza_sdk/resources/geocode"
require_relative "plaza_sdk/resources/map_match"
require_relative "plaza_sdk/resources/optimize"
require_relative "plaza_sdk/resources/query"
require_relative "plaza_sdk/resources/routing"
require_relative "plaza_sdk/resources/search"
require_relative "plaza_sdk/resources/tiles"
