module PlazaSDK
  class Client < PlazaSDK::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    ENVIRONMENTS: {
      production: "https://plaza.fyi",
      local: "http://localhost:4000"
    }

    attr_reader api_key: String

    attr_reader elements: PlazaSDK::Resources::Elements

    attr_reader datasets: PlazaSDK::Resources::Datasets

    attr_reader geocode: PlazaSDK::Resources::Geocode

    attr_reader search: PlazaSDK::Resources::Search

    attr_reader routing: PlazaSDK::Resources::Routing

    attr_reader elevation: PlazaSDK::Resources::Elevation

    attr_reader map_match: PlazaSDK::Resources::MapMatch

    attr_reader optimize: PlazaSDK::Resources::Optimize

    attr_reader query: PlazaSDK::Resources::Query

    attr_reader tiles: PlazaSDK::Resources::Tiles

    private def auth_headers: -> ::Hash[String, String]

    def initialize: (
      ?api_key: String?,
      ?environment: :production | :local | nil,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
