module PlazaSDK
  class AutocompleteResult = PlazaSDK::Models::AutocompleteResult

  class BatchRequest = PlazaSDK::Models::BatchRequest

  class Dataset = PlazaSDK::Models::Dataset

  class DatasetCreateParams = PlazaSDK::Models::DatasetCreateParams

  class DatasetDeleteParams = PlazaSDK::Models::DatasetDeleteParams

  class DatasetFeaturesParams = PlazaSDK::Models::DatasetFeaturesParams

  class DatasetList = PlazaSDK::Models::DatasetList

  class DatasetListParams = PlazaSDK::Models::DatasetListParams

  class DatasetRetrieveParams = PlazaSDK::Models::DatasetRetrieveParams

  class ElementBatchParams = PlazaSDK::Models::ElementBatchParams

  class ElementNearbyParams = PlazaSDK::Models::ElementNearbyParams

  class ElementQueryParams = PlazaSDK::Models::ElementQueryParams

  class ElementRetrieveParams = PlazaSDK::Models::ElementRetrieveParams

  class ElevationBatchParams = PlazaSDK::Models::ElevationBatchParams

  class ElevationBatchResult = PlazaSDK::Models::ElevationBatchResult

  class ElevationLookupParams = PlazaSDK::Models::ElevationLookupParams

  class ElevationLookupResult = PlazaSDK::Models::ElevationLookupResult

  class ElevationProfileParams = PlazaSDK::Models::ElevationProfileParams

  class ElevationProfileRequest = PlazaSDK::Models::ElevationProfileRequest

  class ElevationProfileResult = PlazaSDK::Models::ElevationProfileResult

  class Error = PlazaSDK::Models::Error

  class FeatureCollection = PlazaSDK::Models::FeatureCollection

  class GeocodeAutocompleteParams = PlazaSDK::Models::GeocodeAutocompleteParams

  class GeocodeBatchParams = PlazaSDK::Models::GeocodeBatchParams

  class GeocodeForwardParams = PlazaSDK::Models::GeocodeForwardParams

  class GeocodeResult = PlazaSDK::Models::GeocodeResult

  class GeocodeReverseParams = PlazaSDK::Models::GeocodeReverseParams

  class GeocodingFeature = PlazaSDK::Models::GeocodingFeature

  class GeoJsonFeature = PlazaSDK::Models::GeoJsonFeature

  class GeoJsonGeometry = PlazaSDK::Models::GeoJsonGeometry

  class MapMatchMatchParams = PlazaSDK::Models::MapMatchMatchParams

  class MapMatchRequest = PlazaSDK::Models::MapMatchRequest

  class MapMatchResult = PlazaSDK::Models::MapMatchResult

  class MatrixRequest = PlazaSDK::Models::MatrixRequest

  class MatrixResult = PlazaSDK::Models::MatrixResult

  class NearestResult = PlazaSDK::Models::NearestResult

  class OptimizeCompletedResult = PlazaSDK::Models::OptimizeCompletedResult

  class OptimizeCreateParams = PlazaSDK::Models::OptimizeCreateParams

  class OptimizeJobStatus = PlazaSDK::Models::OptimizeJobStatus

  class OptimizeProcessingResult = PlazaSDK::Models::OptimizeProcessingResult

  class OptimizeRequest = PlazaSDK::Models::OptimizeRequest

  module OptimizeResult = PlazaSDK::Models::OptimizeResult

  class OptimizeRetrieveParams = PlazaSDK::Models::OptimizeRetrieveParams

  class OverpassQuery = PlazaSDK::Models::OverpassQuery

  class QueryOverpassParams = PlazaSDK::Models::QueryOverpassParams

  class QuerySparqlParams = PlazaSDK::Models::QuerySparqlParams

  class ReverseGeocodeResult = PlazaSDK::Models::ReverseGeocodeResult

  class RouteRequest = PlazaSDK::Models::RouteRequest

  class RouteResult = PlazaSDK::Models::RouteResult

  class RoutingIsochroneParams = PlazaSDK::Models::RoutingIsochroneParams

  class RoutingMatrixParams = PlazaSDK::Models::RoutingMatrixParams

  class RoutingNearestParams = PlazaSDK::Models::RoutingNearestParams

  class RoutingRouteParams = PlazaSDK::Models::RoutingRouteParams

  class SearchQueryParams = PlazaSDK::Models::SearchQueryParams

  class SparqlQuery = PlazaSDK::Models::SparqlQuery

  class SparqlResult = PlazaSDK::Models::SparqlResult

  class TileGetParams = PlazaSDK::Models::TileGetParams
end
