module Plaza
  module Models
    type batch_request = { elements: ::Array[Plaza::BatchRequest::Element] }

    class BatchRequest < Plaza::Internal::Type::BaseModel
      attr_accessor elements: ::Array[Plaza::BatchRequest::Element]

      def initialize: (elements: ::Array[Plaza::BatchRequest::Element]) -> void

      def to_hash: -> { elements: ::Array[Plaza::BatchRequest::Element] }

      type element =
        { id: Integer, type: Plaza::Models::BatchRequest::Element::type_ }

      class Element < Plaza::Internal::Type::BaseModel
        attr_accessor id: Integer

        attr_accessor type: Plaza::Models::BatchRequest::Element::type_

        def initialize: (
          id: Integer,
          type: Plaza::Models::BatchRequest::Element::type_
        ) -> void

        def to_hash: -> {
          id: Integer,
          type: Plaza::Models::BatchRequest::Element::type_
        }

        type type_ = :node | :way | :relation

        module Type
          extend Plaza::Internal::Type::Enum

          NODE: :node
          WAY: :way
          RELATION: :relation

          def self?.values: -> ::Array[Plaza::Models::BatchRequest::Element::type_]
        end
      end
    end
  end
end
