module Plaza
  module Models
    type element_lookup_params =
      {  } & Plaza::Internal::Type::request_parameters

    class ElementLookupParams < Plaza::Internal::Type::BaseModel
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      def initialize: (?request_options: Plaza::request_opts) -> void

      def to_hash: -> { request_options: Plaza::RequestOptions }
    end
  end
end
