module Plaza
  module Models
    type elevation_profile_params =
      {  } & Plaza::Internal::Type::request_parameters

    class ElevationProfileParams < Plaza::Models::ElevationProfileRequest
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      def initialize: (?request_options: Plaza::request_opts) -> void

      def to_hash: -> { request_options: Plaza::RequestOptions }
    end
  end
end
