module Plaza
  module Models
    type elevation_lookup_params =
      {
        format_: String,
        lat: Float,
        lng: Float,
        locations: String,
        output_fields: String,
        output_include: String,
        output_precision: Integer
      }
      & Plaza::Internal::Type::request_parameters

    class ElevationLookupParams < Plaza::Internal::Type::BaseModel
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      attr_reader format_: String?

      def format_=: (String) -> String

      attr_reader lat: Float?

      def lat=: (Float) -> Float

      attr_reader lng: Float?

      def lng=: (Float) -> Float

      attr_reader locations: String?

      def locations=: (String) -> String

      attr_reader output_fields: String?

      def output_fields=: (String) -> String

      attr_reader output_include: String?

      def output_include=: (String) -> String

      attr_reader output_precision: Integer?

      def output_precision=: (Integer) -> Integer

      def initialize: (
        ?format_: String,
        ?lat: Float,
        ?lng: Float,
        ?locations: String,
        ?output_fields: String,
        ?output_include: String,
        ?output_precision: Integer,
        ?request_options: Plaza::request_opts
      ) -> void

      def to_hash: -> {
        format_: String,
        lat: Float,
        lng: Float,
        locations: String,
        output_fields: String,
        output_include: String,
        output_precision: Integer,
        request_options: Plaza::RequestOptions
      }
    end
  end
end
