module Plaza
  module Models
    type elevation_profile_request =
      { coordinates: ::Array[Plaza::ElevationProfileRequest::Coordinate] }

    class ElevationProfileRequest < Plaza::Internal::Type::BaseModel
      attr_accessor coordinates: ::Array[Plaza::ElevationProfileRequest::Coordinate]

      def initialize: (
        coordinates: ::Array[Plaza::ElevationProfileRequest::Coordinate]
      ) -> void

      def to_hash: -> {
        coordinates: ::Array[Plaza::ElevationProfileRequest::Coordinate]
      }

      type coordinate = { lat: Float, lng: Float }

      class Coordinate < Plaza::Internal::Type::BaseModel
        attr_accessor lat: Float

        attr_accessor lng: Float

        def initialize: (lat: Float, lng: Float) -> void

        def to_hash: -> { lat: Float, lng: Float }
      end
    end
  end
end
