module Plaza
  module Models
    type elevation_lookup_params =
      { lat: Float, lng: Float, locations: String }
      & Plaza::Internal::Type::request_parameters

    class ElevationLookupParams < Plaza::Internal::Type::BaseModel
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      attr_reader lat: Float?

      def lat=: (Float) -> Float

      attr_reader lng: Float?

      def lng=: (Float) -> Float

      attr_reader locations: String?

      def locations=: (String) -> String

      def initialize: (
        ?lat: Float,
        ?lng: Float,
        ?locations: String,
        ?request_options: Plaza::request_opts
      ) -> void

      def to_hash: -> {
        lat: Float,
        lng: Float,
        locations: String,
        request_options: Plaza::RequestOptions
      }
    end
  end
end
