module Plaza
  module Models
    type elevation_profile_request = { geometry: Plaza::LineStringGeometry }

    class ElevationProfileRequest < Plaza::Internal::Type::BaseModel
      attr_accessor geometry: Plaza::LineStringGeometry

      def initialize: (geometry: Plaza::LineStringGeometry) -> void

      def to_hash: -> { geometry: Plaza::LineStringGeometry }
    end
  end
end
