module Plaza
  module Models
    type elevation_batch_params =
      { coordinates: ::Array[Plaza::ElevationBatchParams::Coordinate] }
      & Plaza::Internal::Type::request_parameters

    class ElevationBatchParams < Plaza::Internal::Type::BaseModel
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      attr_accessor coordinates: ::Array[Plaza::ElevationBatchParams::Coordinate]

      def initialize: (
        coordinates: ::Array[Plaza::ElevationBatchParams::Coordinate],
        ?request_options: Plaza::request_opts
      ) -> void

      def to_hash: -> {
        coordinates: ::Array[Plaza::ElevationBatchParams::Coordinate],
        request_options: Plaza::RequestOptions
      }

      type coordinate = { lat: Float, lng: Float }

      class Coordinate < Plaza::Internal::Type::BaseModel
        attr_accessor lat: Float

        attr_accessor lng: Float

        def initialize: (lat: Float, lng: Float) -> void

        def to_hash: -> { lat: Float, lng: Float }
      end
    end
  end
end
