module Plaza
  module Models
    type error = { error: Plaza::Error::Error }

    class Error < Plaza::Internal::Type::BaseModel
      attr_accessor error: Plaza::Error::Error

      def initialize: (error: Plaza::Error::Error) -> void

      def to_hash: -> { error: Plaza::Error::Error }

      type error =
        { code: String, message: String, details: ::Hash[Symbol, top]? }

      class Error < Plaza::Internal::Type::BaseModel
        attr_accessor code: String

        attr_accessor message: String

        attr_accessor details: ::Hash[Symbol, top]?

        def initialize: (
          code: String,
          message: String,
          ?details: ::Hash[Symbol, top]?
        ) -> void

        def to_hash: -> {
          code: String,
          message: String,
          details: ::Hash[Symbol, top]?
        }
      end
    end
  end
end
