module Plaza
  module Models
    type feature_retrieve_params =
      { type: String, id: Integer } & Plaza::Internal::Type::request_parameters

    class FeatureRetrieveParams < Plaza::Internal::Type::BaseModel
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      attr_accessor type: String

      attr_accessor id: Integer

      def initialize: (
        type: String,
        id: Integer,
        ?request_options: Plaza::request_opts
      ) -> void

      def to_hash: -> {
        type: String,
        id: Integer,
        request_options: Plaza::RequestOptions
      }
    end
  end
end
