module Plaza
  module Models
    type feature_collection =
      {
        features: ::Array[Plaza::GeoJsonFeature],
        type: Plaza::Models::FeatureCollection::type_
      }

    class FeatureCollection < Plaza::Internal::Type::BaseModel
      attr_accessor features: ::Array[Plaza::GeoJsonFeature]

      attr_accessor type: Plaza::Models::FeatureCollection::type_

      def initialize: (
        features: ::Array[Plaza::GeoJsonFeature],
        type: Plaza::Models::FeatureCollection::type_
      ) -> void

      def to_hash: -> {
        features: ::Array[Plaza::GeoJsonFeature],
        type: Plaza::Models::FeatureCollection::type_
      }

      type type_ = :FeatureCollection

      module Type
        extend Plaza::Internal::Type::Enum

        FEATURE_COLLECTION: :FeatureCollection

        def self?.values: -> ::Array[Plaza::Models::FeatureCollection::type_]
      end
    end
  end
end
