module Plaza
  module Models
    type geocoding_feature =
      {
        geometry: Plaza::Models::geometry,
        properties: Plaza::GeocodingFeature::Properties,
        type: Plaza::Models::GeocodingFeature::type_
      }

    class GeocodingFeature < Plaza::Internal::Type::BaseModel
      attr_accessor geometry: Plaza::Models::geometry

      attr_accessor properties: Plaza::GeocodingFeature::Properties

      attr_accessor type: Plaza::Models::GeocodingFeature::type_

      def initialize: (
        geometry: Plaza::Models::geometry,
        properties: Plaza::GeocodingFeature::Properties,
        type: Plaza::Models::GeocodingFeature::type_
      ) -> void

      def to_hash: -> {
        geometry: Plaza::Models::geometry,
        properties: Plaza::GeocodingFeature::Properties,
        type: Plaza::Models::GeocodingFeature::type_
      }

      type properties =
        {
          display_name: String,
          category: String?,
          city: String?,
          confidence: Float?,
          country: String?,
          country_code: String?,
          distance_m: Float?,
          full_address: String?,
          house_number: String?,
          interpolated: bool?,
          name: String?,
          osm_id: Integer?,
          osm_type: Plaza::Models::GeocodingFeature::Properties::osm_type?,
          postcode: String?,
          score: Float?,
          source: Plaza::Models::GeocodingFeature::Properties::source?,
          state: String?,
          street: String?,
          subcategory: String?,
          tags: ::Hash[Symbol, String]?,
          wikipedia: String?
        }

      class Properties < Plaza::Internal::Type::BaseModel
        attr_accessor display_name: String

        attr_accessor category: String?

        attr_accessor city: String?

        attr_accessor confidence: Float?

        attr_accessor country: String?

        attr_accessor country_code: String?

        attr_accessor distance_m: Float?

        attr_accessor full_address: String?

        attr_accessor house_number: String?

        attr_accessor interpolated: bool?

        attr_accessor name: String?

        attr_accessor osm_id: Integer?

        attr_accessor osm_type: Plaza::Models::GeocodingFeature::Properties::osm_type?

        attr_accessor postcode: String?

        attr_accessor score: Float?

        attr_accessor source: Plaza::Models::GeocodingFeature::Properties::source?

        attr_accessor state: String?

        attr_accessor street: String?

        attr_accessor subcategory: String?

        attr_accessor tags: ::Hash[Symbol, String]?

        attr_accessor wikipedia: String?

        def initialize: (
          display_name: String,
          ?category: String?,
          ?city: String?,
          ?confidence: Float?,
          ?country: String?,
          ?country_code: String?,
          ?distance_m: Float?,
          ?full_address: String?,
          ?house_number: String?,
          ?interpolated: bool?,
          ?name: String?,
          ?osm_id: Integer?,
          ?osm_type: Plaza::Models::GeocodingFeature::Properties::osm_type?,
          ?postcode: String?,
          ?score: Float?,
          ?source: Plaza::Models::GeocodingFeature::Properties::source?,
          ?state: String?,
          ?street: String?,
          ?subcategory: String?,
          ?tags: ::Hash[Symbol, String]?,
          ?wikipedia: String?
        ) -> void

        def to_hash: -> {
          display_name: String,
          category: String?,
          city: String?,
          confidence: Float?,
          country: String?,
          country_code: String?,
          distance_m: Float?,
          full_address: String?,
          house_number: String?,
          interpolated: bool?,
          name: String?,
          osm_id: Integer?,
          osm_type: Plaza::Models::GeocodingFeature::Properties::osm_type?,
          postcode: String?,
          score: Float?,
          source: Plaza::Models::GeocodingFeature::Properties::source?,
          state: String?,
          street: String?,
          subcategory: String?,
          tags: ::Hash[Symbol, String]?,
          wikipedia: String?
        }

        type osm_type = :node | :way | :relation

        module OsmType
          extend Plaza::Internal::Type::Enum

          NODE: :node
          WAY: :way
          RELATION: :relation

          def self?.values: -> ::Array[Plaza::Models::GeocodingFeature::Properties::osm_type]
        end

        type source = :structured | :fuzzy | :address | :place | :interpolation

        module Source
          extend Plaza::Internal::Type::Enum

          STRUCTURED: :structured
          FUZZY: :fuzzy
          ADDRESS: :address
          PLACE: :place
          INTERPOLATION: :interpolation

          def self?.values: -> ::Array[Plaza::Models::GeocodingFeature::Properties::source]
        end
      end

      type type_ = :Feature

      module Type
        extend Plaza::Internal::Type::Enum

        FEATURE: :Feature

        def self?.values: -> ::Array[Plaza::Models::GeocodingFeature::type_]
      end
    end
  end
end
