module Plaza
  module Models
    type geocode_reverse_post_params =
      {
        lang: String,
        lat: Float,
        layer: String,
        limit: Integer,
        lng: Float,
        near: String,
        radius: Integer
      }
      & Plaza::Internal::Type::request_parameters

    class GeocodeReversePostParams < Plaza::Internal::Type::BaseModel
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      attr_reader lang: String?

      def lang=: (String) -> String

      attr_reader lat: Float?

      def lat=: (Float) -> Float

      attr_reader layer: String?

      def layer=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader lng: Float?

      def lng=: (Float) -> Float

      attr_reader near: String?

      def near=: (String) -> String

      attr_reader radius: Integer?

      def radius=: (Integer) -> Integer

      def initialize: (
        ?lang: String,
        ?lat: Float,
        ?layer: String,
        ?limit: Integer,
        ?lng: Float,
        ?near: String,
        ?radius: Integer,
        ?request_options: Plaza::request_opts
      ) -> void

      def to_hash: -> {
        lang: String,
        lat: Float,
        layer: String,
        limit: Integer,
        lng: Float,
        near: String,
        radius: Integer,
        request_options: Plaza::RequestOptions
      }
    end
  end
end
