module Plaza
  module Models
    type geocode_batch_params =
      { addresses: ::Array[String] } & Plaza::Internal::Type::request_parameters

    class GeocodeBatchParams < Plaza::Internal::Type::BaseModel
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      attr_accessor addresses: ::Array[String]

      def initialize: (
        addresses: ::Array[String],
        ?request_options: Plaza::request_opts
      ) -> void

      def to_hash: -> {
        addresses: ::Array[String],
        request_options: Plaza::RequestOptions
      }
    end
  end
end
