module Plaza
  module Models
    type geocode_reverse_params =
      {
        lat: Float,
        lng: Float,
        lang: String,
        layer: String,
        limit: Integer,
        radius: Integer
      }
      & Plaza::Internal::Type::request_parameters

    class GeocodeReverseParams < Plaza::Internal::Type::BaseModel
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      attr_accessor lat: Float

      attr_accessor lng: Float

      attr_reader lang: String?

      def lang=: (String) -> String

      attr_reader layer: String?

      def layer=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader radius: Integer?

      def radius=: (Integer) -> Integer

      def initialize: (
        lat: Float,
        lng: Float,
        ?lang: String,
        ?layer: String,
        ?limit: Integer,
        ?radius: Integer,
        ?request_options: Plaza::request_opts
      ) -> void

      def to_hash: -> {
        lat: Float,
        lng: Float,
        lang: String,
        layer: String,
        limit: Integer,
        radius: Integer,
        request_options: Plaza::RequestOptions
      }
    end
  end
end
