module Plaza
  module Models
    type map_match_match_params =
      {  } & Plaza::Internal::Type::request_parameters

    class MapMatchMatchParams < Plaza::Models::MapMatchRequest
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      def initialize: (?request_options: Plaza::request_opts) -> void

      def to_hash: -> { request_options: Plaza::RequestOptions }
    end
  end
end
