module Plaza
  module Models
    type optimize_request =
      {
        waypoints: ::Array[Plaza::OptimizeRequest::Waypoint],
        mode: Plaza::Models::OptimizeRequest::mode,
        roundtrip: bool
      }

    class OptimizeRequest < Plaza::Internal::Type::BaseModel
      attr_accessor waypoints: ::Array[Plaza::OptimizeRequest::Waypoint]

      attr_reader mode: Plaza::Models::OptimizeRequest::mode?

      def mode=: (
        Plaza::Models::OptimizeRequest::mode
      ) -> Plaza::Models::OptimizeRequest::mode

      attr_reader roundtrip: bool?

      def roundtrip=: (bool) -> bool

      def initialize: (
        waypoints: ::Array[Plaza::OptimizeRequest::Waypoint],
        ?mode: Plaza::Models::OptimizeRequest::mode,
        ?roundtrip: bool
      ) -> void

      def to_hash: -> {
        waypoints: ::Array[Plaza::OptimizeRequest::Waypoint],
        mode: Plaza::Models::OptimizeRequest::mode,
        roundtrip: bool
      }

      type waypoint = { lat: Float, lng: Float }

      class Waypoint < Plaza::Internal::Type::BaseModel
        attr_accessor lat: Float

        attr_accessor lng: Float

        def initialize: (lat: Float, lng: Float) -> void

        def to_hash: -> { lat: Float, lng: Float }
      end

      type mode = :auto | :foot | :bicycle

      module Mode
        extend Plaza::Internal::Type::Enum

        AUTO: :auto
        FOOT: :foot
        BICYCLE: :bicycle

        def self?.values: -> ::Array[Plaza::Models::OptimizeRequest::mode]
      end
    end
  end
end
