module Plaza
  module Models
    type optimize_request =
      {
        waypoints: Plaza::MultiPointGeometry,
        mode: Plaza::Models::OptimizeRequest::mode,
        roundtrip: bool
      }

    class OptimizeRequest < Plaza::Internal::Type::BaseModel
      attr_accessor waypoints: Plaza::MultiPointGeometry

      attr_reader mode: Plaza::Models::OptimizeRequest::mode?

      def mode=: (
        Plaza::Models::OptimizeRequest::mode
      ) -> Plaza::Models::OptimizeRequest::mode

      attr_reader roundtrip: bool?

      def roundtrip=: (bool) -> bool

      def initialize: (
        waypoints: Plaza::MultiPointGeometry,
        ?mode: Plaza::Models::OptimizeRequest::mode,
        ?roundtrip: bool
      ) -> void

      def to_hash: -> {
        waypoints: Plaza::MultiPointGeometry,
        mode: Plaza::Models::OptimizeRequest::mode,
        roundtrip: bool
      }

      type mode = :auto | :foot | :bicycle

      module Mode
        extend Plaza::Internal::Type::Enum

        AUTO: :auto
        FOOT: :foot
        BICYCLE: :bicycle

        def self?.values: -> ::Array[Plaza::Models::OptimizeRequest::mode]
      end
    end
  end
end
