module Plaza
  module Models
    type optimize_job_status =
      {
        status: Plaza::Models::OptimizeJobStatus::status,
        result: Plaza::OptimizeCompletedResult?
      }

    class OptimizeJobStatus < Plaza::Internal::Type::BaseModel
      attr_accessor status: Plaza::Models::OptimizeJobStatus::status

      attr_accessor result: Plaza::OptimizeCompletedResult?

      def initialize: (
        status: Plaza::Models::OptimizeJobStatus::status,
        ?result: Plaza::OptimizeCompletedResult?
      ) -> void

      def to_hash: -> {
        status: Plaza::Models::OptimizeJobStatus::status,
        result: Plaza::OptimizeCompletedResult?
      }

      type status = :completed | :processing

      module Status
        extend Plaza::Internal::Type::Enum

        COMPLETED: :completed
        PROCESSING: :processing

        def self?.values: -> ::Array[Plaza::Models::OptimizeJobStatus::status]
      end
    end
  end
end
