module Plaza
  module Models
    type optimize_job_status =
      {
        status: Plaza::Models::OptimizeJobStatus::status,
        error: String?,
        result: top?
      }

    class OptimizeJobStatus < Plaza::Internal::Type::BaseModel
      attr_accessor status: Plaza::Models::OptimizeJobStatus::status

      attr_accessor error: String?

      attr_accessor result: top?

      def initialize: (
        status: Plaza::Models::OptimizeJobStatus::status,
        ?error: String?,
        ?result: top?
      ) -> void

      def to_hash: -> {
        status: Plaza::Models::OptimizeJobStatus::status,
        error: String?,
        result: top?
      }

      type status = :completed | :processing | :failed

      module Status
        extend Plaza::Internal::Type::Enum

        COMPLETED: :completed
        PROCESSING: :processing
        FAILED: :failed

        def self?.values: -> ::Array[Plaza::Models::OptimizeJobStatus::status]
      end
    end
  end
end
