module Plaza
  module Models
    type optimize_retrieve_params =
      { job_id: String } & Plaza::Internal::Type::request_parameters

    class OptimizeRetrieveParams < Plaza::Internal::Type::BaseModel
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      attr_accessor job_id: String

      def initialize: (
        job_id: String,
        ?request_options: Plaza::request_opts
      ) -> void

      def to_hash: -> { job_id: String, request_options: Plaza::RequestOptions }
    end
  end
end
