module Plaza
  module Models
    type plazaql_query = { data: String }

    class PlazaqlQuery < Plaza::Internal::Type::BaseModel
      attr_accessor data: String

      def initialize: (data: String) -> void

      def to_hash: -> { data: String }
    end
  end
end
