module Plaza
  module Models
    type query_execute_params =
      { steps: ::Array[Plaza::QueryExecuteParams::Step] }
      & Plaza::Internal::Type::request_parameters

    class QueryExecuteParams < Plaza::Internal::Type::BaseModel
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      attr_accessor steps: ::Array[Plaza::QueryExecuteParams::Step]

      def initialize: (
        steps: ::Array[Plaza::QueryExecuteParams::Step],
        ?request_options: Plaza::request_opts
      ) -> void

      def to_hash: -> {
        steps: ::Array[Plaza::QueryExecuteParams::Step],
        request_options: Plaza::RequestOptions
      }

      type step =
        { type: Plaza::Models::QueryExecuteParams::Step::type_, query: String }

      class Step < Plaza::Internal::Type::BaseModel
        attr_accessor type: Plaza::Models::QueryExecuteParams::Step::type_

        attr_reader query: String?

        def query=: (String) -> String

        def initialize: (
          type: Plaza::Models::QueryExecuteParams::Step::type_,
          ?query: String
        ) -> void

        def to_hash: -> {
          type: Plaza::Models::QueryExecuteParams::Step::type_,
          query: String
        }

        type type_ = :overpass | :sparql | :filter | :transform

        module Type
          extend Plaza::Internal::Type::Enum

          OVERPASS: :overpass
          SPARQL: :sparql
          FILTER: :filter
          TRANSFORM: :transform

          def self?.values: -> ::Array[Plaza::Models::QueryExecuteParams::Step::type_]
        end
      end
    end
  end
end
