module Plaza
  module Models
    type routing_route_params =
      { format_: String } & Plaza::Internal::Type::request_parameters

    class RoutingRouteParams < Plaza::Models::RouteRequest
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      def format_: -> String?

      def format_=: (String _) -> String

      def initialize: (
        ?format_: String,
        ?request_options: Plaza::request_opts
      ) -> void

      def to_hash: -> {
        format_: String,
        request_options: Plaza::RequestOptions
      }
    end
  end
end
