module Plaza
  module Models
    type routing_nearest_post_params =
      {
        lat: Float,
        lng: Float,
        output_fields: String,
        output_include: String,
        output_precision: Integer,
        radius: Integer
      }
      & Plaza::Internal::Type::request_parameters

    class RoutingNearestPostParams < Plaza::Internal::Type::BaseModel
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      attr_accessor lat: Float

      attr_accessor lng: Float

      attr_reader output_fields: String?

      def output_fields=: (String) -> String

      attr_reader output_include: String?

      def output_include=: (String) -> String

      attr_reader output_precision: Integer?

      def output_precision=: (Integer) -> Integer

      attr_reader radius: Integer?

      def radius=: (Integer) -> Integer

      def initialize: (
        lat: Float,
        lng: Float,
        ?output_fields: String,
        ?output_include: String,
        ?output_precision: Integer,
        ?radius: Integer,
        ?request_options: Plaza::request_opts
      ) -> void

      def to_hash: -> {
        lat: Float,
        lng: Float,
        output_fields: String,
        output_include: String,
        output_precision: Integer,
        radius: Integer,
        request_options: Plaza::RequestOptions
      }
    end
  end
end
