module Plaza
  module Models
    type route_request =
      {
        destination: Plaza::RouteRequest::Destination,
        origin: Plaza::RouteRequest::Origin,
        alternatives: Integer,
        annotations: bool,
        depart_at: Time?,
        ev: Plaza::RouteRequest::Ev?,
        exclude: String?,
        geometries: Plaza::Models::RouteRequest::geometries,
        mode: Plaza::Models::RouteRequest::mode,
        overview: Plaza::Models::RouteRequest::overview,
        steps: bool,
        traffic_model: Plaza::Models::RouteRequest::traffic_model?,
        waypoints: ::Array[Plaza::RouteRequest::Waypoint]?
      }

    class RouteRequest < Plaza::Internal::Type::BaseModel
      attr_accessor destination: Plaza::RouteRequest::Destination

      attr_accessor origin: Plaza::RouteRequest::Origin

      attr_reader alternatives: Integer?

      def alternatives=: (Integer) -> Integer

      attr_reader annotations: bool?

      def annotations=: (bool) -> bool

      attr_accessor depart_at: Time?

      attr_accessor ev: Plaza::RouteRequest::Ev?

      attr_accessor exclude: String?

      attr_reader geometries: Plaza::Models::RouteRequest::geometries?

      def geometries=: (
        Plaza::Models::RouteRequest::geometries
      ) -> Plaza::Models::RouteRequest::geometries

      attr_reader mode: Plaza::Models::RouteRequest::mode?

      def mode=: (
        Plaza::Models::RouteRequest::mode
      ) -> Plaza::Models::RouteRequest::mode

      attr_reader overview: Plaza::Models::RouteRequest::overview?

      def overview=: (
        Plaza::Models::RouteRequest::overview
      ) -> Plaza::Models::RouteRequest::overview

      attr_reader steps: bool?

      def steps=: (bool) -> bool

      attr_accessor traffic_model: Plaza::Models::RouteRequest::traffic_model?

      attr_accessor waypoints: ::Array[Plaza::RouteRequest::Waypoint]?

      def initialize: (
        destination: Plaza::RouteRequest::Destination,
        origin: Plaza::RouteRequest::Origin,
        ?alternatives: Integer,
        ?annotations: bool,
        ?depart_at: Time?,
        ?ev: Plaza::RouteRequest::Ev?,
        ?exclude: String?,
        ?geometries: Plaza::Models::RouteRequest::geometries,
        ?mode: Plaza::Models::RouteRequest::mode,
        ?overview: Plaza::Models::RouteRequest::overview,
        ?steps: bool,
        ?traffic_model: Plaza::Models::RouteRequest::traffic_model?,
        ?waypoints: ::Array[Plaza::RouteRequest::Waypoint]?
      ) -> void

      def to_hash: -> {
        destination: Plaza::RouteRequest::Destination,
        origin: Plaza::RouteRequest::Origin,
        alternatives: Integer,
        annotations: bool,
        depart_at: Time?,
        ev: Plaza::RouteRequest::Ev?,
        exclude: String?,
        geometries: Plaza::Models::RouteRequest::geometries,
        mode: Plaza::Models::RouteRequest::mode,
        overview: Plaza::Models::RouteRequest::overview,
        steps: bool,
        traffic_model: Plaza::Models::RouteRequest::traffic_model?,
        waypoints: ::Array[Plaza::RouteRequest::Waypoint]?
      }

      type destination = { lat: Float, lng: Float }

      class Destination < Plaza::Internal::Type::BaseModel
        attr_accessor lat: Float

        attr_accessor lng: Float

        def initialize: (lat: Float, lng: Float) -> void

        def to_hash: -> { lat: Float, lng: Float }
      end

      type origin = { lat: Float, lng: Float }

      class Origin < Plaza::Internal::Type::BaseModel
        attr_accessor lat: Float

        attr_accessor lng: Float

        def initialize: (lat: Float, lng: Float) -> void

        def to_hash: -> { lat: Float, lng: Float }
      end

      type ev =
        {
          battery_capacity_wh: Float,
          connector_types: ::Array[String]?,
          initial_charge_pct: Float,
          min_charge_pct: Float,
          min_power_kw: Float?
        }

      class Ev < Plaza::Internal::Type::BaseModel
        attr_accessor battery_capacity_wh: Float

        attr_accessor connector_types: ::Array[String]?

        attr_reader initial_charge_pct: Float?

        def initial_charge_pct=: (Float) -> Float

        attr_reader min_charge_pct: Float?

        def min_charge_pct=: (Float) -> Float

        attr_accessor min_power_kw: Float?

        def initialize: (
          battery_capacity_wh: Float,
          ?connector_types: ::Array[String]?,
          ?initial_charge_pct: Float,
          ?min_charge_pct: Float,
          ?min_power_kw: Float?
        ) -> void

        def to_hash: -> {
          battery_capacity_wh: Float,
          connector_types: ::Array[String]?,
          initial_charge_pct: Float,
          min_charge_pct: Float,
          min_power_kw: Float?
        }
      end

      type geometries = :geojson | :polyline | :polyline6

      module Geometries
        extend Plaza::Internal::Type::Enum

        GEOJSON: :geojson
        POLYLINE: :polyline
        POLYLINE6: :polyline6

        def self?.values: -> ::Array[Plaza::Models::RouteRequest::geometries]
      end

      type mode = :auto | :foot | :bicycle

      module Mode
        extend Plaza::Internal::Type::Enum

        AUTO: :auto
        FOOT: :foot
        BICYCLE: :bicycle

        def self?.values: -> ::Array[Plaza::Models::RouteRequest::mode]
      end

      type overview = :full | :simplified | :false

      module Overview
        extend Plaza::Internal::Type::Enum

        FULL: :full
        SIMPLIFIED: :simplified
        FALSE: :false

        def self?.values: -> ::Array[Plaza::Models::RouteRequest::overview]
      end

      type traffic_model = :best_guess | :optimistic | :pessimistic

      module TrafficModel
        extend Plaza::Internal::Type::Enum

        BEST_GUESS: :best_guess
        OPTIMISTIC: :optimistic
        PESSIMISTIC: :pessimistic

        def self?.values: -> ::Array[Plaza::Models::RouteRequest::traffic_model]
      end

      type waypoint = { lat: Float, lng: Float }

      class Waypoint < Plaza::Internal::Type::BaseModel
        attr_accessor lat: Float

        attr_accessor lng: Float

        def initialize: (lat: Float, lng: Float) -> void

        def to_hash: -> { lat: Float, lng: Float }
      end
    end
  end
end
