module Plaza
  module Models
    type routing_route_params = {  } & Plaza::Internal::Type::request_parameters

    class RoutingRouteParams < Plaza::Models::RouteRequest
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      def initialize: (?request_options: Plaza::request_opts) -> void

      def to_hash: -> { request_options: Plaza::RequestOptions }
    end
  end
end
