module Plaza
  module Models
    type routing_isochrone_params =
      { lat: Float, lng: Float, time: Float, mode: String }
      & Plaza::Internal::Type::request_parameters

    class RoutingIsochroneParams < Plaza::Internal::Type::BaseModel
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      attr_accessor lat: Float

      attr_accessor lng: Float

      attr_accessor time: Float

      attr_reader mode: String?

      def mode=: (String) -> String

      def initialize: (
        lat: Float,
        lng: Float,
        time: Float,
        ?mode: String,
        ?request_options: Plaza::request_opts
      ) -> void

      def to_hash: -> {
        lat: Float,
        lng: Float,
        time: Float,
        mode: String,
        request_options: Plaza::RequestOptions
      }
    end
  end
end
