module Plaza
  module Models
    type search_query_params =
      { q: String, cursor: String, limit: Integer }
      & Plaza::Internal::Type::request_parameters

    class SearchQueryParams < Plaza::Internal::Type::BaseModel
      extend Plaza::Internal::Type::RequestParameters::Converter
      include Plaza::Internal::Type::RequestParameters

      attr_accessor q: String

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize: (
        q: String,
        ?cursor: String,
        ?limit: Integer,
        ?request_options: Plaza::request_opts
      ) -> void

      def to_hash: -> {
        q: String,
        cursor: String,
        limit: Integer,
        request_options: Plaza::RequestOptions
      }
    end
  end
end
