module PlazaSDK
  module Resources
    class Elements
      def retrieve: (
        Integer id,
        type: String,
        ?request_options: PlazaSDK::request_opts
      ) -> PlazaSDK::GeoJsonFeature

      def batch: (
        elements: ::Array[PlazaSDK::BatchRequest::Element],
        ?request_options: PlazaSDK::request_opts
      ) -> PlazaSDK::FeatureCollection

      def nearby: (
        lat: Float,
        lng: Float,
        ?limit: Integer,
        ?radius: Integer,
        ?request_options: PlazaSDK::request_opts
      ) -> PlazaSDK::FeatureCollection

      def query: (
        ?bbox: String,
        ?cursor: String,
        ?h3: String,
        ?limit: Integer,
        ?type: String,
        ?request_options: PlazaSDK::request_opts
      ) -> PlazaSDK::FeatureCollection

      def initialize: (client: PlazaSDK::Client) -> void
    end
  end
end
