module PlazaSDK
  module Resources
    class Geocode
      def autocomplete: (
        q: String,
        ?country_code: String,
        ?lang: String,
        ?lat: Float,
        ?layer: String,
        ?limit: Integer,
        ?lng: Float,
        ?request_options: PlazaSDK::request_opts
      ) -> PlazaSDK::AutocompleteResult

      def batch: (
        addresses: ::Array[String],
        ?request_options: PlazaSDK::request_opts
      ) -> top

      def forward: (
        q: String,
        ?bbox: String,
        ?country_code: String,
        ?lang: String,
        ?lat: Float,
        ?layer: String,
        ?limit: Integer,
        ?lng: Float,
        ?request_options: PlazaSDK::request_opts
      ) -> PlazaSDK::GeocodeResult

      def reverse: (
        lat: Float,
        lng: Float,
        ?lang: String,
        ?layer: String,
        ?limit: Integer,
        ?radius: Integer,
        ?request_options: PlazaSDK::request_opts
      ) -> PlazaSDK::ReverseGeocodeResult

      def initialize: (client: PlazaSDK::Client) -> void
    end
  end
end
