module PlazaSDK
  module Resources
    class Optimize
      def create: (
        waypoints: PlazaSDK::GeoJsonGeometry,
        ?mode: PlazaSDK::Models::OptimizeRequest::mode,
        ?roundtrip: bool,
        ?request_options: PlazaSDK::request_opts
      ) -> PlazaSDK::Models::optimize_result

      def retrieve: (
        String job_id,
        ?request_options: PlazaSDK::request_opts
      ) -> PlazaSDK::OptimizeJobStatus

      def initialize: (client: PlazaSDK::Client) -> void
    end
  end
end
