module PlazaSDK
  module Resources
    class Query
      def overpass: (
        data: String,
        ?request_options: PlazaSDK::request_opts
      ) -> PlazaSDK::FeatureCollection

      def sparql: (
        query: String,
        ?request_options: PlazaSDK::request_opts
      ) -> PlazaSDK::SparqlResult

      def initialize: (client: PlazaSDK::Client) -> void
    end
  end
end
