module PlazaSDK
  module Resources
    class Tiles
      def get: (
        Integer y_,
        z: Integer,
        x: Integer,
        ?request_options: PlazaSDK::request_opts
      ) -> StringIO

      def initialize: (client: PlazaSDK::Client) -> void
    end
  end
end
